create table if not exists public.plantalk_rooms (
  share_code text primary key,
  room jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plantalk_info_logs (
  id bigint generated by default as identity primary key,
  user_code text not null,
  room_code text,
  action text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists plantalk_rooms_set_updated_at on public.plantalk_rooms;

create trigger plantalk_rooms_set_updated_at
before update on public.plantalk_rooms
for each row
execute function public.set_updated_at();

alter table public.plantalk_rooms enable row level security;
alter table public.plantalk_info_logs enable row level security;

drop policy if exists "Plantalk rooms are readable by share link" on public.plantalk_rooms;
drop policy if exists "Plantalk rooms can be created by app users" on public.plantalk_rooms;
drop policy if exists "Plantalk rooms can be updated by app users" on public.plantalk_rooms;

create policy "Plantalk rooms are readable by share link"
on public.plantalk_rooms
for select
to anon
using (true);

create policy "Plantalk rooms can be created by app users"
on public.plantalk_rooms
for insert
to anon
with check (true);

create policy "Plantalk rooms can be updated by app users"
on public.plantalk_rooms
for update
to anon
using (true)
with check (true);

drop policy if exists "Plantalk logs can be created by app users" on public.plantalk_info_logs;

create policy "Plantalk logs can be created by app users"
on public.plantalk_info_logs
for insert
to anon
with check (true);
